---
version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: CodeDeploy/Deploy.sh
      runas: root
  ApplicationStart:
    - location: CodeDeploy/Run.sh
      runas: apache