field: a15f32e4-4a86-4115-a772-32d226c18bb3 # Role Reactions
fieldLayouts:
  a1e0555a-2279-4e97-ae39-d4eb84db3e30:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 67c11f6a-251d-49db-bd06-f9cadf4fe71f # Emoji
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ebdf38e5-64b1-4a72-9924-563e7443d83d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 856dfb4d-fe6e-40ab-a661-335264a0e20d # Role
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c735460-3d36-44be-bbf8-d90cce8b2a28
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4a5d35a7-478f-419d-8205-ced8b74e1724 # Description (Optional)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eca1e4a1-d68f-4d44-848c-fae216170b61
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 9ca5914b-e969-4b90-8fb2-b05cb7395a4f
        userCondition: null
fields:
  4a5d35a7-478f-419d-8205-ced8b74e1724: # Description (Optional)
    columnSuffix: vscvffue
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: null
    name: 'Description (Optional)'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  67c11f6a-251d-49db-bd06-f9cadf4fe71f: # Emoji
    columnSuffix: scxewmvy
    contentColumnType: string
    fieldGroup: null
    handle: emoji
    instructions: null
    name: Emoji
    searchable: false
    settings:
      dropdownType: null
    translationKeyFormat: null
    translationMethod: none
    type: magi\fields\EmojiField
  856dfb4d-fe6e-40ab-a661-335264a0e20d: # Role
    columnSuffix: sjlvhkvn
    contentColumnType: string
    fieldGroup: null
    handle: role
    instructions: null
    name: Role
    searchable: false
    settings:
      dropdownType: null
    translationKeyFormat: null
    translationMethod: none
    type: magi\fields\RoleField
handle: roleReaction
name: 'Role Reaction'
sortOrder: 1
