field: a944b172-1299-4510-86cc-5179b31a16c3 # Dummy
fieldLayouts:
  c4e6b3c1-8018-4ce6-8e97-711360fa9ca5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ceceaef8-25a3-49a3-af8c-2c692930e623 # Drop One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3289708d-2237-4c15-b90f-36835b1055d1
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 20c1e22c-93fe-4926-a0b6-e6fab6a95f8c # Drop 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68e39a85-8e2a-4905-8f8a-21c09c1d4de2
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: aba057c0-446a-403d-b653-6ac5ef9fd099
        userCondition: null
fields:
  20c1e22c-93fe-4926-a0b6-e6fab6a95f8c: # Drop 2
    columnSuffix: xritabgz
    contentColumnType: string
    fieldGroup: null
    handle: drop2
    instructions: null
    name: 'Drop 2'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Barfoo
            -
              - value
              - barfoo
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Bar
            -
              - value
              - bar
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ceceaef8-25a3-49a3-af8c-2c692930e623: # Drop One
    columnSuffix: ehiuztum
    contentColumnType: string
    fieldGroup: null
    handle: dropOne
    instructions: null
    name: 'Drop One'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Foobar
            -
              - value
              - foobar
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Foo
            -
              - value
              - foo
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: row
name: Row
sortOrder: 1
