fieldLayouts:
  fda19f35-8773-45b3-a04a-ed68fbf8c269:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 77ba6ba7-bdce-42ad-9a9a-f6c1c753276d
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 7a0feb03-e9fb-4dc4-a537-7c671dcd98b9 # Date
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4aef0966-7fe2-4ae5-90a5-aed40f54df74
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a8de57bc-969d-4abc-b67a-0a7111943914 # Guild
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d55027ff-d302-406c-b631-6016329e6f4d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 146ac2e6-294d-4b03-9e17-a5ddb448f6ae # Channel
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd567490-5a65-4813-ae7f-7b45cd200651
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 6ede746b-3f1e-412f-8ca7-ae5aea7b7269 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8e759b9-9533-4813-96ee-b76553f8714e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: a819cbfe-ca29-4bd9-81f0-9dca60fa1f96 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ba144464-3403-4074-b964-3c3893f5b29c
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: magi\fields\conditions\GuildFieldConditionRule
                  fieldUid: a8de57bc-969d-4abc-b67a-0a7111943914 # Guild
                  operator: notempty
                  uid: 43df6b53-be99-4034-9474-3411b633fce2
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: 3a2936de-287e-4f48-9583-5301ba20812f # Vote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8ba95ab8-9c7d-4e94-a950-9a018a40c09a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 45da819f-ffd1-43d9-8d94-0d8f8fb369b8
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 9634b7f6-688a-4ba0-bd9c-22aae8c35c1f # Message ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49d6ab85-495c-473b-bb87-99a031efba69
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8818550e-e2a2-4518-a241-413c1343817e # Riot Night Role ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 86d8f35e-26e6-41e3-8d4e-e742f5713ddd
            userCondition: null
            warning: null
            width: 100
        name: Discord
        uid: d39b0b0d-9427-47b4-bc69-bfbbcf6e73a6
        userCondition: null
handle: riotNight
hasTitleField: true
name: 'Riot Night'
section: 910bfc8c-0352-4ba0-8d56-d8eb1bad6642 # Messages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
