fieldLayouts:
  004e423d-0037-4a4d-b6c6-b94fb12577ed:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8bf10546-21af-4c96-ae24-36a340e4b5b8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d0304d62-acc7-4a67-a47a-2cc2ef18f3a5 # Channel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 27e785e9-904d-4700-aa22-87c161e0c789
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 834c084a-22a4-4349-bb98-09b79287b031 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 724876be-989a-42ed-8dae-7a3f50238a6b
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f85139d1-963d-4e84-b2e6-c0cb03058e56 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2754139-21fd-49cd-a660-25525016e3d3
            userCondition: null
            warning: null
            width: 75
          -
            elementCondition: null
            fieldUid: 9c695049-9bc1-4830-bbcf-85fc63810f1a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6566c362-4c5c-4b04-9479-bd4fe97b8702
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3e7e4f47-a727-495f-acfa-419271f133b7 # Vote Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 765bcfb7-3d4c-4b5a-8eda-6d290bc56aee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 58fe90e7-a2da-42b0-824e-748cedbbbdd3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5b758ccd-1188-439f-94d3-4657cdbb946f # Message ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed381838-5185-42db-9315-297ddf81b8f0
            userCondition: null
            warning: null
            width: 100
        name: Discord
        uid: de334b60-d407-4540-b718-271b2bae291f
        userCondition: null
handle: vote
hasTitleField: true
name: Vote
section: 24cd6242-b981-46a7-a383-94e20a10f825 # Messages
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
