field: 360a65e4-aa70-44a6-a829-4233645609cd # Roles / Emojis
fieldLayouts:
  56b68152-5f09-4a19-9a9b-82f0c994e065:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: dcfa73be-67a8-492b-9a0b-733ecaaa5ab0 # Role
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1c0a0662-6d6b-4716-8c25-e04d9f666338
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 1b6ee14a-6a63-4adf-84b1-e2d5bb3cf971 # Emoji
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 895431f2-b332-4030-859e-dc2816342bfe
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: ca800fc0-edee-4878-9a1a-92bbbbb84481
        userCondition: null
fields:
  1b6ee14a-6a63-4adf-84b1-e2d5bb3cf971: # Emoji
    columnSuffix: fblvqfbq
    contentColumnType: string
    fieldGroup: null
    handle: emoji
    instructions: null
    name: Emoji
    searchable: false
    settings:
      dropdownType: emojis
    translationKeyFormat: null
    translationMethod: none
    type: discordbot\fields\DiscordDropdownField
  dcfa73be-67a8-492b-9a0b-733ecaaa5ab0: # Role
    columnSuffix: lqqconwb
    contentColumnType: string
    fieldGroup: null
    handle: role
    instructions: null
    name: Role
    searchable: false
    settings:
      dropdownType: roles
    translationKeyFormat: null
    translationMethod: none
    type: discordbot\fields\DiscordDropdownField
handle: roleEmoji
name: 'Role / Emoji'
sortOrder: 1
