field: 3e7e4f47-a727-495f-acfa-419271f133b7 # Vote Options
fieldLayouts:
  22c05595-111f-421a-8702-8ea7f0fa6434:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fb1fe643-92b2-4ade-890a-cd30edbc5fad # Emoji
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9cfbba0c-aed2-4f2b-b4e4-83663a4017ec
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 56ff0b20-7013-4554-b5cf-f03f15461258 # Option
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 58d32715-ca44-499f-bab3-e7e1d4dc0652
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 3c32ec4b-0053-4873-88ae-65407a805547
        userCondition: null
fields:
  56ff0b20-7013-4554-b5cf-f03f15461258: # Option
    columnSuffix: ogjjwokv
    contentColumnType: text
    fieldGroup: null
    handle: option
    instructions: null
    name: Option
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fb1fe643-92b2-4ade-890a-cd30edbc5fad: # Emoji
    columnSuffix: plopyrht
    contentColumnType: string
    fieldGroup: null
    handle: emoji
    instructions: null
    name: Emoji
    searchable: false
    settings:
      dropdownType: emojis
    translationKeyFormat: null
    translationMethod: none
    type: discordbot\fields\DiscordDropdownField
handle: vote
name: Vote
sortOrder: 1
