fieldLayouts:
  6667a322-10b3-43af-85fc-b7564d666804:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 756c1083-4699-41d6-8b96-789b19b176b5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 834c084a-22a4-4349-bb98-09b79287b031 # Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c66e10f1-a566-4754-ae4d-a87aafe147f1
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f85139d1-963d-4e84-b2e6-c0cb03058e56 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a4f66f0-eb3a-4d90-927c-c1a3c1784167
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: 787d9d30-094b-4147-be28-671e2afcaed7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5b758ccd-1188-439f-94d3-4657cdbb946f # Message ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 755bdcfd-2cae-41a7-a254-8492702b1dc8
            userCondition: null
            warning: null
            width: 100
        name: 'Discord Info'
        uid: 0431404d-45d1-416d-9aee-d46b46dfa538
        userCondition: null
handle: roleReaction
hasTitleField: true
name: 'Role Reaction'
section: 24cd6242-b981-46a7-a383-94e20a10f825 # Messages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
