columnSuffix: hbmdpkbk
contentColumnType: string
fieldGroup: eed0a146-3d97-49c7-8d92-1b7f8f5aa612 # Common
handle: rolesEmojis
instructions: null
name: 'Roles / Emojis'
searchable: false
settings:
  contentTable: '{{%matrixcontent_rolesemojis}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
