fieldLayouts:
  88941acd-0340-4181-a139-b7ea54e4dd2e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: b9255ebf-2914-4988-a9d3-730e35d9d471
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 393edaee-3cfa-413b-9519-ebef9b47fc67
        userCondition: null
fs: aws
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
