fieldLayouts:
  15aced4d-c352-4ad3-9d3e-01a4b2d7b561:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: eea07341-62c6-42ef-881a-f57bf1f2fa42
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f99288c4-6a13-4e4a-add9-33d903139e61
        userCondition: null
fs: awsS3
handle: images
name: Images
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
