columnSuffix: khbcykln
contentColumnType: string
fieldGroup: eed0a146-3d97-49c7-8d92-1b7f8f5aa612 # Common
handle: channel
instructions: null
name: Channel
searchable: false
settings:
  dropdownType: channels
translationKeyFormat: null
translationMethod: none
type: discordbot\fields\DiscordDropdownField
