columnSuffix: lzffjdiy
contentColumnType: datetime
fieldGroup: 659cbc52-ae52-4589-bf73-f30c52bbe2f7 # Common
handle: date
instructions: null
name: Date
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 60
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
