columnSuffix: lvihujvc
contentColumnType: text
fieldGroup: eed0a146-3d97-49c7-8d92-1b7f8f5aa612 # Common
handle: discordMessageId
instructions: null
name: 'Discord Message ID'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
