columnSuffix: gaxjrhmz
contentColumnType: string
fieldGroup: 659cbc52-ae52-4589-bf73-f30c52bbe2f7 # Common
handle: voiceChannel
instructions: null
name: 'Voice Channel'
searchable: false
settings:
  channelType: voice
  dropdownType: null
translationKeyFormat: null
translationMethod: none
type: magi\fields\ChannelField
