defaultPlacement: end
enableVersioning: false
handle: messages
name: Messages
propagationMethod: all
siteSettings:
  8ed46d22-b609-4bea-82d8-b99f480dc2a7: # Magi
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
